server:
  port: 8765

spring:
  application:
    name: api-gateway

#    It is used to identify all the services registered in eureka server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#          To make service id in lower case
          lowerCaseServiceId: true

#It is not needed to be client of eureka server but for security we did it
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
