server:
  port: 8765

spring:
  application:
    name: api-gateway

#    It is used to identify all the services registered in eureka server
  cloud:
    gateway:

#      Now we do not have to specify the service name in url
      routes:
        - id: CURRENCY-EXCHANGE-SERVICE
          uri: lb://CURRENCY-EXCHANGE-SERVICE
          predicates:
            - Path= /currency-exchange/**
        - id: AUTHENTICATION-SERVICE
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path= /auth/**



#      discovery:
#        locator:
#          enabled: true

#          To make service id in lower case
#          lowerCaseServiceId: true


#It is not needed to be client of eureka server but for security we did it
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
